.TH SACD 1 "08 Nov 2018" "18.6.25" "User Manual"

.SH NAME
sacd \- Super Audio CD decoder

.SH SYNOPSIS
sacd \fB-i\fP infile [\fB-o\fP outdir] [options]

.SH OPTIONS
.TP
-i, --infile
Specify the input file (*.iso, *.dsf, *.dff)
.TP
-o, --outdir
The folder to write the WAVE files to. If you omit
this, the files will be placed in the input file's
directory
.TP
-c, --stdout
Stdout output (for pipe), sample:
.br
sacd -i file.dsf -c | play -
.TP
-r, --rate
The output samplerate.
Valid rates are: 88200, 96000, 176400 and 192000.
If you omit this, 96KHz will be used.
.TP
-p, --progress
Display progress to new lines. Use this if you intend
to parse the output through a script. This option only
lists either one progress percentage per line, or one
status/error message.
.TP
-s, --stereo
Only extract the 2-channel area if it exists.
If you omit this, the multichannel area will have priority.
.TP
-h, --help
Show help message

.SH AUTHOR
Robert Tari <robert.tari@gmail.com>
.br
https://tari.in/www/software/sacd/